services:
  database:
    container_name: db_dev
    image: postgres:15.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_NON_ROOT_USER: db-user
      POSTGRES_NON_ROOT_USER_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: updraft-interview
    volumes:
      - updraft_interview_pg_db:/var/lib/postgresql/data
      - ./database/init-scripts:/docker-entrypoint-initdb.d
      - ./database/scripts:/usr/app
    ports:
      - "5445:5432"
    networks:
      - updraft

  backend:
    container_name: backend_dev
    build:
      context: ./backend
      target: development
    image: backend
    env_file:
      - ./backend/.env
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/usr/app
    command: ./scripts/run-dev.sh
    networks:
      - updraft

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      target: development
    image: frontend
    environment:
      - NODE_ENV=development
    ports:
      - "5180:5180" # expose Vite port externally
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - updraft

  nginx:
    image: nginx
    container_name: nginx_dev
    build:
      context: ./nginx
      target: development
    environment:
      - FRONTEND_HOST=frontend:5180
      - API_HOST=backend:3003/api
    depends_on:
      - frontend
      - backend
    ports:
      - "8090:80"
    networks:
      - updraft

volumes:
  updraft_interview_pg_db:

networks:
  updraft:
    name: updraft
    driver: bridge
