"""documents

Revision ID: f3b9c4319171
Revises: 
Create Date: 2025-07-08 15:47:11.268706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b9c4319171'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
      sa.Column('id', sa.UUID(), nullable=False),
      sa.Column('title', sa.String(length=255), nullable=False),
      sa.Column('content_html', sa.String(), nullable=False),
      sa.Column('created_at', sa.DateTime(), nullable=False),
      sa.Column('archived_at', sa.DateTime(), nullable=True),
      sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_archived_at_search', 'documents', ['archived_at'], unique=False)
    op.create_index('idx_documents_id_search', 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_documents_id_search', table_name='documents')
    op.drop_index('idx_documents_archived_at_search', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
